default_platform(:ios)

platform :ios do
  desc "Deploy to App Store Connect (TestFlight)"
  lane :internal do
    # Automatically increase the build number
    increment_build_number(xcodeproj: "Runner.xcodeproj")

    # Build the app
    build_app(
      workspace: "Runner.xcworkspace",
      scheme: "Runner",
      export_method: "app-store", # ad-hoc|package
      export_options: {
        provisioningProfiles: { 
          "com.ncalteen.flutter_multiplaform" => "iOSDistribution",
        }
      }
    )

    # Generate a JWT to connect to App Store Connect
    app_store_connect_api_key(
      key_id: ENV["APP_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APP_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APP_STORE_CONNECT_KEY_FILE"],
      duration: 1200
    )

    # Upload the app to App Store Connect
    upload_to_testflight(
      apple_id: ENV["APPLE_ID"],
      app_identifier: ENV["APP_BUNDLE_IDENTIFIER"],
      # itc_team_id: ENV["ITC_TEAM_ID"],
      username: ENV["USERNAME"]
    )
  end
end
