# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "App Store (TestFlight)"
  lane :internal do
    # increment_build_number(xcodeproj: "Runner.xcodeproj")
    # build_app(workspace: "Runner.xcworkspace", scheme: "Runner")
    app_store_connect_api_key(
      key_id: ENV["APPLE_STORE_CONNECT_API_KEY_ID"],
      issuer_id: ENV["APPLE_STORE_CONNECT_ISSUER_ID"],
      key_content: ENV["APPLE_STORE_CONNECT_KEY_FILE"],
      duration: 1200
    )
    upload_to_testflight(
      apple_id: ENV["APPLE_ID"],
      app_identifier: ENV["APPLE_APP_ID"],
      ipa: "../build/ios/ipa/*.ipa",
      team_id: ENV["APPLE_TEAM_ID"],
      itc_team_id: ENV["APPLE_ITC_TEAM_ID"]
    )
  end
end
