# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Google Play (Internal)"
  lane :internal do
    setup_ci if ENV['CI']

    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['ANDROID_SERVICE_ACCOUNT_JSON']
    )
  end

  desc "Google Play (Production)"
  lane :production do
    setup_ci if ENV['CI']

    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      json_key_data: ENV['ANDROID_SERVICE_ACCOUNT_JSON']
    )
  end
end
